name = "DifferentialEquationProject1"
uuid = "8f98ef4c-b07f-471c-bf24-613ccdb0b7b0"
authors = ["MasterHamster42 <master_hamster9@protonmail.com>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
